'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,RefreshCw,Search} from 'lucide-react';
import {effectiveLevel,workloadPoints,type DesignData,type DesignTask} from './designer-model';
type Payload=DesignData&{canEdit:boolean};
const normalized=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const periodLabel=(s:string)=>s==='all'?'Tất cả tháng':s==='unknown'?'Chưa ghi tháng':`Tháng ${Number(s.slice(5))}/${s.slice(0,4)}`;
const sortPeriods=(values:string[])=>values.sort((a,b)=>a==='unknown'?1:b==='unknown'?-1:b.localeCompare(a));
const safeUrl=(s:string)=>/^https?:\/\//i.test(s)?s:null;
export default function DesignerPanel(){
  const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState<string|null>(null),[loading,setLoading]=useState(false);
  const [period,setPeriod]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[type,setType]=useState('all'),[page,setPage]=useState(1);
  async function load(){setLoading(true);try{const response=await fetch('/api/designer',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Không tải được dữ liệu.');setData(result);setPeriod(current=>current||sortPeriods([...new Set<string>(result.items.map((x:DesignTask)=>x.period))])[0]||'all');setError('');}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu.');}finally{setLoading(false);}}
  useEffect(()=>{void load()},[]);
  async function changeLevel(item:DesignTask,level:string){
    setSaving(item.id);setError('');setNotice('');
    try{const response=await fetch('/api/designer',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,level:level||null,expectedUpdatedAt:item.updatedAt})});const result=await response.json();if(!response.ok){if(response.status===409)await load();throw new Error(result.error||'Không lưu được level.');}setData(result);setNotice(`Đã lưu level cho task #${item.sheetRow}. Workload Point đã tính lại.`);}catch(e){setError(e instanceof Error?e.message:'Không lưu được level.');}finally{setSaving(null);}
  }
  const rows=useMemo(()=>data?.items.filter(item=>(period==='all'||item.period===period)&&(status==='all'||(status==='done'?item.status.toUpperCase()==='DONE':item.status.toUpperCase()!=='DONE'))&&(type==='all'||item.taskType===type)&&(!query||normalized([item.name,item.platform,item.briefBy,item.note,item.taskType].join(' ')).includes(normalized(query))))||[],[data,period,status,type,query]);
  const periods=sortPeriods([...new Set(data?.items.map(x=>x.period)||[])]);
  const types=[...new Set(data?.items.map(x=>x.taskType)||[])].sort((a,b)=>a.localeCompare(b,'vi'));
  const done=rows.filter(x=>x.status.toUpperCase()==='DONE');
  const totalPoints=data?rows.reduce((sum,x)=>sum+(workloadPoints(x,data)??0),0):0;
  const donePoints=data?done.reduce((sum,x)=>sum+(workloadPoints(x,data)??0),0):0;
  const unscored=data?rows.filter(x=>workloadPoints(x,data)===null).length:0;
  const pages=Math.max(1,Math.ceil(rows.length/25)),currentPage=Math.min(page,pages),visible=rows.slice((currentPage-1)*25,currentPage*25);
  const filter=(fn:()=>void)=>{fn();setPage(1)};
  return <>
    <div className="page-heading"><div><p className="eyebrow">KHÔNG GIAN LÀM VIỆC / DESIGNER</p><h1>Designer</h1><p>Task thiết kế từ BRIEF DESIGN · điểm theo KPI CONFIG 2026.</p></div><button className="button outline" disabled={loading||!!saving} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'Đang tải…':'Tải lại'}</button></div>
    {error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert success">{notice}</div>}
    {!data&&!error&&<div className="loading-state">Đang tải task Designer…</div>}
    {data&&<>
      <div className="tools-row designer-filters"><label className="search-box"><Search size={17}/><input aria-label="Tìm task Designer" placeholder="Tìm task, người brief…" value={query} onChange={e=>filter(()=>setQuery(e.target.value))}/></label><select aria-label="Lọc tháng Designer" value={period} onChange={e=>filter(()=>setPeriod(e.target.value))}><option value="all">Tất cả tháng</option>{periods.map(p=><option key={p} value={p}>{periodLabel(p)}</option>)}</select><select aria-label="Lọc loại task" value={type} onChange={e=>filter(()=>setType(e.target.value))}><option value="all">Tất cả loại task</option>{types.map(t=><option key={t} value={t}>{t||'Chưa phân loại'}</option>)}</select><select aria-label="Lọc tiến độ Designer" value={status} onChange={e=>filter(()=>setStatus(e.target.value))}><option value="all">Tất cả tiến độ</option><option value="done">Hoàn thành</option><option value="open">Chưa hoàn thành</option></select></div>
      <div className="list-lead-stats designer-stats"><div className="list-lead-stat"><span>Tổng task</span><strong>{rows.length}</strong><small>{periodLabel(period)}</small></div><div className="list-lead-stat"><span>Workload Point</span><strong>{totalPoints}</strong><small>Tổng điểm trong bộ lọc</small></div><div className="list-lead-stat"><span>Điểm hoàn thành</span><strong>{donePoints}</strong><small>{done.length} task DONE</small></div><div className="list-lead-stat"><span>Điểm còn lại</span><strong>{totalPoints-donePoints}</strong><small>{rows.length-done.length} task chưa DONE</small></div></div>
      {unscored>0&&<p className="data-note">{unscored} task chưa có level hoặc phân loại phù hợp; chưa cộng vào tổng điểm.</p>}
      <details className="panel designer-rules"><summary>Quy tắc chấm điểm L1–L5</summary><p>Ưu tiên level chọn trên dashboard, tiếp đến level trong file, rồi level mặc định theo loại task. Chọn “Theo file / phân loại” để bỏ lựa chọn riêng trên dashboard.</p><div className="designer-levels">{data.levels.map(level=><div key={level.id}><strong>{level.id} · {level.short} · {level.points} điểm</strong><p>{level.description}</p><details><summary>Dấu hiệu và ví dụ</summary><p>{level.signals}</p><p className="designer-prewrap">{level.examples}</p></details></div>)}</div></details>
      {!data.canEdit&&<p className="data-note">Tài khoản chỉ xem. Quản trị viên cấp quyền Designer trong mục Người dùng để chọn level.</p>}
      <section className="panel data-panel"><div className="panel-title"><div><h2>Danh sách thiết kế</h2><p>{rows.length} task · {periodLabel(period)}</p></div></div><div className="table-scroll"><table className="designer-table"><thead><tr><th>Task / Nền tảng</th><th>Phân loại</th><th>Người brief</th><th>Ngày brief</th><th>Deadline</th><th>Tiến độ</th><th>Complexity Level</th><th>Workload Point</th><th>Brief / Final</th><th>Ghi chú</th></tr></thead><tbody>{visible.map(item=>{const level=effectiveLevel(item,data),points=workloadPoints(item,data);return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.platform||'Chưa ghi nền tảng'} · {periodLabel(item.period)} · Dòng {item.sheetRow}</small></td><td>{item.taskType||'Chưa phân loại'}</td><td>{item.briefBy||'—'}</td><td>{item.briefDate||'—'}</td><td>{item.deadline||'—'}</td><td><span className={`pill ${item.status.toUpperCase()==='DONE'?'contacted':'new'}`}>{item.status||'Chưa ghi'}</span></td><td>{data.canEdit?<select className="designer-select" aria-label={`Complexity Level cho ${item.name}`} value={item.levelOverride||''} disabled={!!saving||loading} onChange={e=>void changeLevel(item,e.target.value)}><option value="">Theo file / phân loại{level&&!item.levelOverride?` (${level})`:''}</option>{data.levels.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select>:<span>{data.levels.find(l=>l.id===level)?.label||'Chưa có level'}</span>}{saving===item.id&&<small role="status">Đang lưu…</small>}</td><td className="designer-points"><strong>{points??'—'}</strong><small>{level||'Chưa có level'}</small></td><td>{safeUrl(item.briefUrl)&&<a href={item.briefUrl} target="_blank" rel="noopener noreferrer">Brief</a>} {safeUrl(item.finalUrl)&&<a href={item.finalUrl} target="_blank" rel="noopener noreferrer">Final</a>}{!safeUrl(item.briefUrl)&&!safeUrl(item.finalUrl)&&'—'}</td><td>{item.note?<details><summary>Xem ghi chú</summary><p className="designer-prewrap">{item.note}</p></details>:'—'}</td></tr>})}</tbody></table></div>{!rows.length&&<p className="list-lead-no-result">Không tìm thấy task phù hợp.</p>}<div className="list-lead-pagination"><span>{rows.length?`${(currentPage-1)*25+1}–${Math.min(currentPage*25,rows.length)} / ${rows.length}`:'0 task'}</span><div><button disabled={currentPage===1} aria-label="Trang trước" onClick={()=>setPage(currentPage-1)}><ChevronLeft size={17}/></button><span>Trang {currentPage}/{pages}</span><button disabled={currentPage===pages} aria-label="Trang sau" onClick={()=>setPage(currentPage+1)}><ChevronRight size={17}/></button></div></div></section>
      <p className="data-note">Dữ liệu nhập từ {data.sourceName}. Tháng theo nhóm trong file; ngày brief và deadline giữ theo dữ liệu nguồn. Level chọn ở đây được lưu trên dashboard.</p>
    </>}
  </>;
}
