'use client';
import { useEffect,useState } from 'react';
type User={email:string;displayName:string;role:'viewer'|'designer'};
export default function UserAccessPanel(){
  const [users,setUsers]=useState<User[]>([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [role,setRole]=useState<'viewer'|'designer'>('viewer');
  async function changeRole(user:User,role:string){setError('');const response=await fetch('/api/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,role})});if(!response.ok){setError('Không cập nhật được quyền.');return}setNotice('Đã cập nhật quyền.');void load()}
  async function load(){const response=await fetch('/api/users',{cache:'no-store'});if(response.ok)setUsers((await response.json()).users)}
  useEffect(()=>{void load()},[]);
  async function submit(event:React.FormEvent){event.preventDefault();setError('');const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,displayName:name,password,role})});const result=await response.json();if(!response.ok){setError(result.error||'Không tạo được tài khoản.');return}setEmail('');setName('');setPassword('');setNotice('Đã tạo tài khoản. Gửi tài khoản và mật khẩu cho người dùng qua kênh riêng.');void load()}
  async function remove(user:User){if(!window.confirm(`Thu hồi quyền của ${user.email}?`))return;const response=await fetch('/api/users',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email})});if(!response.ok){setError('Không thu hồi được quyền.');return}void load()}
  return <><div className="page-heading"><div><p className="eyebrow">KHÔNG GIAN LÀM VIỆC / QUYỀN TRUY CẬP</p><h1>Người dùng</h1><p>Cấp quyền xem hoặc quyền Designer để chọn Complexity Level.</p></div></div><section className="panel access-panel"><h2>Cấp tài khoản</h2><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Tên hiển thị<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Mật khẩu ban đầu<input type="password" required minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Quyền<select value={role} onChange={e=>setRole(e.target.value as 'viewer'|'designer')}><option value="viewer">Chỉ xem</option><option value="designer">Designer · chọn level</option></select></label><button className="button primary">Tạo tài khoản</button></form>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p className="data-note">{notice}</p>}</section><section className="panel access-panel"><h2>Tài khoản đã cấp</h2>{users.map(user=><div className="access-user" key={user.email}><span><strong>{user.displayName}</strong><small>{user.email}</small></span><select aria-label={`Quyền của ${user.email}`} value={user.role||'viewer'} onChange={e=>void changeRole(user,e.target.value)}><option value="viewer">Chỉ xem</option><option value="designer">Designer</option></select><button className="button outline" onClick={()=>void remove(user)}>Thu hồi</button></div>)}{!users.length&&<p className="data-note">Chưa cấp tài khoản.</p>}</section></>;
}

